name: "Jellyseerr Server"
description: "Jellyseerr Server Plugin"
version: "0.1.0"
slug: "jellyseerr"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5055/tcp: 5055
